### PR TITLE
added general hive tuning

### PR DESCRIPTION
**Pull request by grierdavid**
Based on best practices recommendations some Hive default tuning is added

### CODE REVIEW

**Comment by ahoybender** [comment]
Can one of the admins verify this patch?

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
recheck this please

**Comment by ahoybender** [comment]
recheck this please

**Comment by ahoybender** [comment]
recheck this please

**Comment by ahoybender** [comment]
please recheck this

**Comment by ahoybender** [comment]
recheck this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by grierdavid** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Comment by ahoybender** [comment]
retest this please

**Pull request merged**
