### PR TITLE
Adding Spark support

### PR DESCRIPTION
**Pull request by grierdavid**

### CODE REVIEW

**Comment by grierdavid** [comment]
Functional testing performed on rackspace public cloud

**Comment by shintasmith** [comment]
oooo is this for the HDP 2.2??? (cc @usnavi)

**Comment by grierdavid** [comment]
Yep! This is for HDP 2.2.4

**Comment by shintasmith** [comment]
Very nice! :+1:

**Comment by grierdavid** [comment]
Thanks! :)

**Pull request merged**
