### PR TITLE
Update README.md for Joe Engel

### PR DESCRIPTION
**Pull request by aguynamedjoetoo**
Love my history, but just for legal reasons need to make sure my association with the project is clear. :P Miss you all!

### CODE REVIEW

**Comment by magglass1** [comment]
+1 :cry:

**Comment by aguynamedjoetoo** [comment]
+1 for @magglass1 to go to sleep :|

**Comment by magglass1** [comment]
@Joeskyyy I was Hadoop'n until 8:40pm today. Definitely getting some sleep now. :sleeping:

**Comment by alexandruanghel** [comment]
+1 :cry: 
miss you buddy

**Pull request merged**
